#
#
# This is a sample newrelic_plugin.yml file. Please move this file
# to the following location if it is not already there:
#
#     ./config/newrelic_plugin.yml
#
# Where the current directory is the directory where your main program resides and is your current
# directory when you run the main program.
#
# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '0f8d43dcb7a6a6cedc348f5c410e9bc21189f2e2'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1
#
# Agent Configuration:
#
agents:
  mpstat:
    # The command used to display MP statistics
    command: mpstat
    # Report current usage as the average over this many seconds.
    interval:
